name: Agent Space Cleanup Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  clean-up-space:
    name: Clean up space
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check file space
        run: |
          df -h

      - name: Remove large packages
        run: |
          sudo apt-get purge -y \
            '^llvm-.*' \
            'php.*' \
            '^mongodb-.*' \
            '^mysql-.*' \
            azure-cli \
            google-chrome-stable \
            firefox \
            powershell \
            microsoft-edge-stable \
            mono-devel
          sudo apt-get autoremove -y
          sudo apt-get clean

      - name: Check file space
        run: |
          df -h

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"

      - name: Check file space
        run: |
          df -h

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Check file space
        run: |
          df -h
