name: Test VoiceOver

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-voiceover:
    runs-on: macos-12
    strategy:
      matrix:
        spec: [alert, banner, breadcrumb, checkbox]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Guidepup Setup
        uses: guidepup/setup-action@0.11.2
      - run: yarn install --frozen-lockfile
      - run: yarn test ./tests/${{ matrix.spec }}.spec.ts
      - uses: actions/upload-artifact@v3
        if: always()
        continue-on-error: true
        with:
          name: artifacts
          path: |
            **/test-results/**/*
            **/playwright-report/**/*
            **/recordings/**/*
